// Route paths centralized
export const ROUTES = {
  ADMIN: '/admin',
  DASHBOARD: '/admin/dashboard',
  USERS: '/admin/users',
  USER_DETAIL: (id: string) => `/admin/users/${id}`,
  ORDERS: '/admin/orders',
  ORDER_DETAIL: (id: string) => `/admin/orders/${id}`,
  COUPONS: '/admin/coupons',
  COUPON_DETAIL: (id: string) => `/admin/coupons/${id}`,
  COUPONS_CREATE: '/admin/coupons/create',
  COUPON_EDIT: (id: string) => `/admin/coupons/${id}/edit`,
  PRODUCTS: '/admin/products',
  PRODUCT_DETAIL: (id: string) => `/admin/products/${id}`,
  PRODUCTS_CREATE: '/admin/products/create',
  PRODUCT_EDIT: (id: string) => `/admin/products/${id}/edit`,
  SHIPMENTS: '/admin/shipments',
  SHIPMENT_DETAIL: (id: string) => `/admin/shipments/${id}`,
  PAYMENT_EVENTS: '/admin/payment-events',
  PAYMENT_EVENT_DETAIL: (id: string) => `/admin/payment-events/${id}`,
  BRANDS: '/admin/brands',
  CATEGORIES: '/admin/categories',
  ANALYTICS: '/admin/analytics',
} as const;
